타입 체크시 발생하는 에러 해결
➤ YN0000: [@timespark/components]: .storybook/decorators/withGlobalStyle.decorator.tsx(2,29): error TS6059: File '/Users/reesekimm/dev/timespark-fe/packages/styles/src/index.ts' is not under 'rootDir' '/Users/reesekimm/dev/timespark-fe/packages/components'. 'rootDir' is expected to contain all source files.
➤ YN0000: [@timespark/components]:   The file is in the program because:
➤ YN0000: [@timespark/components]:     Imported via '@timespark/styles' from file '/Users/reesekimm/dev/timespark-fe/packages/components/.storybook/decorators/withGlobalStyle.decorator.tsx'
➤ YN0000: [@timespark/components]:     Imported via '@timespark/styles' from file '/Users/reesekimm/dev/timespark-fe/packages/components/.storybook/decorators/withTheme.decorator.tsx'
➤ YN0000: [@timespark/components]:     Imported via '@timespark/styles' from file '/Users/reesekimm/dev/timespark-fe/packages/components/utils/rtl-utils.tsx'
➤ YN0000: [@timespark/components]:     Matched by include pattern '../styles/src/*' in 'tsconfig.json'
➤ YN0000: [@timespark/components]: ../styles/src/index.ts(3,26): error TS6059: File '/Users/reesekimm/dev/timespark-fe/packages/styles/src/defaultTheme.ts' is not under 'rootDir' '/Users/reesekimm/dev/timespark-fe/packages/components'. 'rootDir' is expected to contain all source files.
➤ YN0000: [@timespark/components]:   The file is in the program because:
➤ YN0000: [@timespark/components]:     Imported via './defaultTheme' from file '/Users/reesekimm/dev/timespark-fe/packages/styles/src/index.ts'
➤ YN0000: [@timespark/components]:     Imported via '../src/defaultTheme' from file '/Users/reesekimm/dev/timespark-fe/packages/styles/@types/styled.d.ts'
➤ YN0000: [@timespark/components]:     Matched by include pattern '../styles/src/*' in 'tsconfig.json'
➤ YN0000: [@timespark/components]:     Imported via './defaultTheme' from file '/Users/reesekimm/dev/timespark-fe/packages/styles/src/index.ts'
➤ YN0000: [@timespark/components]: ../styles/src/index.ts(4,25): error TS6059: File '/Users/reesekimm/dev/timespark-fe/packages/styles/src/globalStyle.tsx' is not under 'rootDir' '/Users/reesekimm/dev/timespark-fe/packages/components'. 'rootDir' is expected to contain all source files.
➤ YN0000: [@timespark/components]:   The file is in the program because:
➤ YN0000: [@timespark/components]:     Imported via './globalStyle' from file '/Users/reesekimm/dev/timespark-fe/packages/styles/src/index.ts'
➤ YN0000: [@timespark/components]:     Matched by include pattern '../styles/src/*' in 'tsconfig.json'
➤ YN0000: [@timespark/components]:     Imported via './globalStyle' from file '/Users/reesekimm/dev/timespark-fe/packages/styles/src/index.ts'

https://stackoverflow.com/a/67370304/12220184

https://yarnpkg.com/features/workspaces#workspace-ranges-workspace